# Generated by Django 5.1.3 on 2024-11-12 04:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pin_code', models.BigIntegerField()),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pan_card', models.CharField(unique=True)),
                ('aadhar_card', models.BigIntegerField(unique=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('family_details', models.TextField()),
                ('martial_status', models.CharField(max_length=150)),
                ('star', models.CharField(max_length=150)),
                ('raasi', models.CharField(max_length=150)),
                ('kootram', models.CharField(max_length=150)),
                ('kuladeivam', models.TextField()),
                ('last_timestamp', models.DateTimeField(auto_now=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
