# Generated by Django 5.1.3 on 2024-11-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='kuladeivam',
            field=models.TextField(blank=True, null=True),
        ),
    ]
